version: '3'

services:
  identitydb:
    restart: always
    environment:
      POSTGRES_PASSWORD: password 
    volumes:
      - postgres-identity-data-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432" 

  identityservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Host=identitydb;Database=identitydb;Username=postgres;Password=password" 
      - IdentityUrl=http://identityservice 
      - SpaClient=http://${EXTERNAL_DNS_NAME_OR_IP}:5100
    ports:
      - "5201:80"
    volumes:
      - ./Services/identitycert:/app/cert

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identityservice 
    ports:
      - "5200:80"
    volumes:
      - ./ApiGateways/apigw:/app/configuration

  productservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identityservice 
    ports:
      - "5101:80"


  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://${EXTERNAL_DNS_NAME_OR_IP}:5201               
      - ProductUrl=http://${EXTERNAL_DNS_NAME_OR_IP}:5200
    ports:
      - "5100:80"


volumes:
  postgres-identity-data-volume: