version: '3'

services:
  identityservice:
    image: identityservice
    build:
      context: .
      dockerfile: Services/IdentityService/Dockerfile

  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: ApiGateways/ApiGateway/Dockerfile

  productservice:
    image: productservice
    build:
      context: .
      dockerfile: Services/ProductService/Dockerfile  


  webapp:
    image: webapp
    build:
      context: .
      dockerfile: Clients/WebApp/Dockerfile
    depends_on:
      - identityservice
      - productservice