version: '3'

services:
  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  productservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

