version: '3.4'

services:
  identitydb:
    image: postgres

  productdb:
    image: postgres

  bookingdb:
    image: postgres

  paymentdb:
    image: postgres

  notificationdb:
    image: postgres

  notificationnosqldb:
    image: mongo

  rabbitmq:
    image: rabbitmq:3.7.5-management-alpine

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.0

  kibana:
    image: docker.elastic.co/kibana/kibana:6.3.0
    depends_on:
     - elasticsearch
    
  identityservice:
    image: identityservice
    build:
      context: .
      dockerfile: Services/IdentityService/Dockerfile
    depends_on:
     - identitydb
#     - elasticsearch

  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: ApiGateways/ApiGateway/Dockerfile
    depends_on:
     - identitydb
     - productdb
     - bookingdb
     - notificationdb
     - notificationnosqldb
#     - elasticsearch
     - identityservice
     - rabbitmq
     - productservice
     - bookingservice
     - notificationservice

  productservice:
    image: productservice
    build:
      context: .
      dockerfile: Services/ProductService/Dockerfile
    depends_on:
     - productdb
     - elasticsearch
     - rabbitmq

  bookingservice:
    image: bookingservice
    build:
      context: .
      dockerfile: Services/BookingService/Dockerfile
    depends_on:
     - bookingdb
#     - elasticsearch
     - rabbitmq

  paymentservice:
    image: paymentservice
    build:
      context: .
      dockerfile: Services/PaymentService/Dockerfile
    depends_on:
     - paymentdb
#     - elasticsearch
     - rabbitmq

  notificationservice:
    image: notificationservice
    build:
      context: .
      dockerfile: Services/NotificationService/Dockerfile
    depends_on:
     - notificationnosqldb
     - notificationdb
#     - elasticsearch
     - rabbitmq

  webapp:
    image: webapp
    build:
      context: .
      dockerfile: Clients/WebApp/Dockerfile
#    depends_on:     
#     - elasticsearch

  webstatus:
    image: webstatus
    build:
      context: .
      dockerfile: Monitoring/WebStatus/Dockerfile
