version: '3'

services:
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: ApiGateways/ApiGateway/Dockerfile

  productservice:
    image: productservice
    build:
      context: .
      dockerfile: Services/ProductService/Dockerfile

