version: '3.4'

services:
  identitydb:
    image: postgres

  productdb:
    image: postgres

  bookingdb:
    image: postgres

  paymentdb:
    image: postgres

  notificationdb:
    image: postgres

  notificationnosqldb:
    image: mongo

  rabbitmq:
    image: rabbitmq:3.7.5-management-alpine
    
  identityservice:
    image: identityservice
    build:
      context: .
      dockerfile: Services/IdentityService/Dockerfile
    depends_on:
     - identitydb

  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: ApiGateways/ApiGateway/Dockerfile

  productservice:
    image: productservice
    build:
      context: .
      dockerfile: Services/ProductService/Dockerfile
    depends_on:
     - productdb
     - rabbitmq

  bookingservice:
    image: bookingservice
    build:
      context: .
      dockerfile: Services/BookingService/Dockerfile
    depends_on:
     - bookingdb
     - rabbitmq

  paymentservice:
    image: paymentservice
    build:
      context: .
      dockerfile: Services/PaymentService/Dockerfile
    depends_on:
     - paymentdb
     - rabbitmq

  notificationservice:
    image: notificationservice
    build:
      context: .
      dockerfile: Services/NotificationService/Dockerfile
    depends_on:
     - notificationnosqldb
     - notificationdb
     - rabbitmq

  webapp:
    image: webapp
    build:
      context: .
      dockerfile: Clients/WebApp/Dockerfile
    depends_on:
      - identityservice
      - productservice
      - bookingservice
  

