version: '3'

services:
  identityservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5201:80"

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identityservice 
    ports:
      - "5200:80"
    volumes:
      - ./ApiGateways/apigw:/app/configuration

  productservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5101:80"


  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5100:80"

