version: '3'

services:
  identityservice:
    image: identityservice
    build:
      context: .
      dockerfile: Services/IdentityService/Dockerfile

  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: ApiGateways/ApiGateway/Dockerfile

  productservice:
    image: productservice
    build:
      context: .
      dockerfile: Services/ProductService/Dockerfile


  

