version: '3'

services:
  identitydb:
    image: postgres
    
  identityservice:
    image: identityservice
    build:
      context: .
      dockerfile: Services/IdentityService/Dockerfile
    depends_on:
     - identitydb

  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: ApiGateways/ApiGateway/Dockerfile

  productservice:
    image: productservice
    build:
      context: .
      dockerfile: Services/ProductService/Dockerfile  


  webapp:
    image: webapp
    build:
      context: .
      dockerfile: Clients/WebApp/Dockerfile
    depends_on:
      - identityservice
      - productservice