version: '3.4'

services:
  identitydb:
    restart: always
    environment:
      POSTGRES_PASSWORD: password 
    volumes:
      - postgres-identity-data-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432" 

  productdb:
    restart: always
    environment:
      POSTGRES_PASSWORD: password 
    volumes:
      - postgres-product-data-volume:/var/lib/postgresql/data
    ports:
      - "5434:5432"
      
  bookingdb:
    restart: always
    environment:
      POSTGRES_PASSWORD: password 
    volumes:
      - postgres-booking-data-volume:/var/lib/postgresql/data
    ports:
      - "5435:5432" 

  paymentdb:
    restart: always
    environment:
      POSTGRES_PASSWORD: password 
    volumes:
      - postgres-payment-data-volume:/var/lib/postgresql/data
    ports:
      - "5436:5432"

  notificationdb:
    restart: always
    environment:
      POSTGRES_PASSWORD: password 
    volumes:
      - postgres-notification-data-volume:/var/lib/postgresql/data
    ports:
      - "5437:5432"

  notificationnosqldb:
    restart: always
    volumes:
      - nosql-notification-data-volume:/data/db
    ports:
      - "27017:27017"

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  elasticsearch:
    volumes:
      - elasticsearch-data-volume:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    ports:
      - "5601:5601"

  identityservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Host=identitydb;Database=identitydb;Username=postgres;Password=password" 
      - IdentityUrl=http://identityservice 
      - SpaClient=http://${EXTERNAL_DNS_NAME_OR_IP}:5100
      - ProductsClient=http://${EXTERNAL_DNS_NAME_OR_IP}:5101
      - BookingClient=http://${EXTERNAL_DNS_NAME_OR_IP}:5102
    ports:
      - "5201:80"
    volumes:
      - ./Services/identitycert:/app/cert

  apigateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://identityservice 
    ports:
      - "5200:80"
    volumes:
      - ./ApiGateways/apigw:/app/configuration

  bookingagg:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development      
      - urls__ProductUrl=http://productservice
      - urls__BookingUrl=http://bookingservice
      - urls__IdentityUrl=http://identityservice
    ports:
      - "5202:80"    

  productservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Host=productdb;Database=productdb;Username=postgres;Password=password"
      - ElasticUrl=http://elasticsearch:9200
      - IdentityUrl=http://identityservice 
      - IdentityUrlExternal=http://${EXTERNAL_DNS_NAME_OR_IP}:5201
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest  
    ports:
      - "5101:80"

  bookingservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Host=bookingdb;Database=bookingdb;Username=postgres;Password=password"
      - IdentityUrl=http://identityservice
      - IdentityUrlExternal=http://${EXTERNAL_DNS_NAME_OR_IP}:5201
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest 
    ports:
      - "5102:80"

  paymentservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Host=paymentdb;Database=paymentdb;Username=postgres;Password=password"      
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest 
    ports:
      - "5103:80"

  notificationservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Host=notificationdb;Database=notificationdb;Username=postgres;Password=password"
      - MongoConnectionString=mongodb://notificationnosqldb     
      - MongoDatabase=PushSubscriptionDb
      - IdentityUrl=http://identityservice
      - EventBusConnection=rabbitmq
      - EventBusUserName=guest
      - EventBusPassword=guest 
    ports:
      - "5104:80"

  webapp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - IdentityUrl=http://${EXTERNAL_DNS_NAME_OR_IP}:5201
      - GatewayApiUrl=http://${EXTERNAL_DNS_NAME_OR_IP}:5200
      - IdentityUrlHC=http://identityservice/hc
      - ProductUrlHC=http://productservice/hc
      - BookingUrlHC=http://bookingservice/hc      
      - PaymentUrlHC=http://paymentservice/hc
      - NotificationUrlHC=http://notificationservice/hc      
    ports:
      - "5100:80"

  webstatus:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
      - IdentityUrl=http://identityservice/hc
      - ProductUrl=http://productservice/hc
      - BookingUrl=http://bookingservice/hc
      - PaymentUrl=http://paymentservice/hc      
      - NotificationUrl=http://notificationservice/hc      
      - spa=http://webapp/hc
    ports:
      - "5105:80"
      

volumes:
  elasticsearch-data-volume:
  postgres-identity-data-volume:
  postgres-product-data-volume:
  postgres-booking-data-volume:
  postgres-payment-data-volume:
  postgres-notification-data-volume:
  nosql-notification-data-volume:

