version: '3'

services:
  apigateway:
    image: apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile

  productservice:
    image: productservice
    build:
      context: .
      dockerfile: ProductService/Dockerfile

