apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "productservice.fullname" . }}
  labels:
    app: {{ template "productservice.name" . }}
    chart: {{ template "productservice.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "productservice.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "productservice.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              value: Host={{ .Values.inf.postgresql.products.host }};Database={{ .Values.inf.postgresql.products.database }};Username={{ .Values.inf.postgresql.common.user }};Password={{ .Values.inf.postgresql.common.password }}
            - name: ElasticUrl
              value: http://{{ .Values.inf.elasticsearch.host }}:9200
            - name: IdentityUrl
              value: http://{{ .Values.app.svc.identity }}
            - name: IdentityUrlExternal
              value: http://{{ .Values.inf.k8s.dns }}/{{ .Values.app.ingress.entries.identity }}
            - name: EventBusConnection
              value: {{ .Values.inf.eventbus.connection }}
            - name: EventBusUserName
              value: {{ .Values.inf.eventbus.user }}
            - name: EventBusPassword
              value: {{ .Values.inf.eventbus.password }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
