apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "apigateway.fullname" . }}
  labels:
    app: {{ template "apigateway.name" . }}
    chart: {{ template "apigateway.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "apigateway.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "apigateway.name" . }}
        release: {{ .Release.Name }}
    spec:
      volumes:
        - name: apigatewayconfig
          configMap:
            name: cfg-{{ template "apigateway.name" . }}
            items:
            - key: configuration.json
              path: configuration.json
      {{ if .Values.inf.registry -}}
      imagePullSecrets:
      - name: {{ .Values.inf.registry.secretName }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ template "fqdn-image" . }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PATH_BASE
              value: {{ .Values.pathBase }}
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: IdentityUrl
              value: http://{{ .Values.inf.k8s.dns }}/{{ .Values.app.ingress.entries.identity }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: apigatewayconfig
              mountPath: /app/configuration
              readOnly: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
