apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-{{ template "apigateway.name" . }}
  labels:
    app: {{ template "apigateway.name" . }}
    chart: {{ template "apigateway.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ (.Files.Glob "configuration.json").AsConfig | indent 2 }}
