apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ template "identityservice.fullname" . }}
  labels:
    app: {{ template "identityservice.name" . }}
    chart: {{ template "identityservice.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "identityservice.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "identityservice.name" . }}
        release: {{ .Release.Name }}
    spec:      
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: PATH_BASE
              value: {{ .Values.pathBase }}
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__DefaultConnection
              value: Host={{ .Values.inf.postgresql.identity.host }};Database={{ .Values.inf.postgresql.identity.database }};Username={{ .Values.inf.postgresql.common.user }};Password={{ .Values.inf.postgresql.common.password }}
            - name: IdentityUrl
              value: http://{{ .Values.inf.k8s.dns }}/{{ .Values.app.ingress.entries.identity }}
            - name: SpaClient
              value: http://{{ .Values.inf.k8s.dns }}
            - name: ProductsClient
              value: http://{{ .Values.inf.k8s.dns }}/{{ .Values.app.ingress.entries.products }}
            - name: BookingClient
              value: http://{{ .Values.inf.k8s.dns }}/{{ .Values.app.ingress.entries.booking }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP          
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
