apiVersion: v1
kind: ConfigMap
metadata:
  name: cfg-{{ template "identityservice.name" . }}
  labels:
    app: {{ template "identityservice.name" . }}
    chart: {{ template "identityservice.chart" .}}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{ (.Files.Glob "configuration.json").AsConfig | indent 2 }}
binarydata:
  {{ (.Files.Glob "idsrv3test.pfx").AsSecrets | indent 2 }}
