app:
  ingress:
    entries:
      identity: identity
      products: products
      booking: booking
      webapp: ""
  svc:
      identity: identityservice
      products: productservice
      booking: bookingservice
      webapp: webapp
